### ISSUE TITLE
Can we host the release on github itself?

### ISSUE THREAD

**Issue by wadkar** [infernoboy/JavaScript-Blocker-5#17]
Github might be a reasonable place to keep the release tarball. What do you think?

**Comment by infernoboy** [comment]
I've thought about this, but after months of monitoring bandwidth and requests usage, there are too many requests made per month to be allowed on GitHub Pages (more than twice as many as they allow). I do post the releases on GitHub; updating won't go through GitHub, though.

**Comment by wadkar** [comment]
It might be possible for those who can setup command line API calls using
their own GITHUB_TOKENS to bypass this. I don't remember exactly where I
got the setup info, but it would be nice to release the tarball with a hash
or something. We can always include a link to the download link in case.
Thoughts?

**Comment by infernoboy** [comment]
The problem is that extensions include a manifest file which must be hosted somewhere that Safari can automatically access. Without that, the extension will never be able to be updated automatically. I suppose I can create a bundle containing the .safariextz file along side a hash file and also include the hash in the release notes on GitHub.

I'm not quite sure what you mean by using GITHUB_TOKENS to bypass it, but I don't think that would apply here.

**Comment by wadkar** [comment]
>
> I suppose I can create a bundle containing the .safariextz file along side
> a hash file and also include the hash in the release notes on GitHub.
>
Yes! This is more than enough. Thanks a lot!

**Comment by infernoboy** [comment]
Just remember: Safari will still be able to update the extension without hash verification. If this is something that concerns you, make sure you are not updating through Safari and instead manually download the files.

**Comment by wadkar** [comment]
Interesting. Thanks a lot for the tip!
