### ISSUE TITLE
Allowing scripts within cloudfront.net doesn't seem to work

### ISSUE THREAD

**Issue by jsit** [infernoboy/JavaScript-Blocker-5#20]
![screen shot 2017-03-23 at 10 34 46 am](https://cloud.githubusercontent.com/assets/643417/24252642/66ad4838-0fb4-11e7-91be-6b0a384729ad.png)
I keep having to allow resources from within cloudfront.net, despite having this rule for all domains set.

For instance, on:
- https://www.indiantypefoundry.com
- https://www.suitcasetype.com

**Comment by infernoboy** [comment]
Hello.

This is due to the way JSB interprets top-level-domains. You are not expected to allow the entirety of "cloudfront.net" because of how broad it is. JSB sees "cloudfront.net <http://cloudfront.net/>" in the same way it sees ".net", i.e., it expects something to be in front of it. It is for this reason the UI doesn't even allow selecting "cloudfront.net <http://cloudfront.net/>" to allow/block. Unfortunately there is no way around this at this time.

Travis~

**Comment by infernoboy** [comment]
Actually, there is a way around it. Sorry for the hasty first email.

Create the rule as a regular expression instead: ^https:\/\/(.+)+\.cloudfront.net <http://cloudfront.net/>/.+$

That should work.

**Comment by infernoboy** [comment]
Actually, there is a way around it. Sorry for the hasty first email.

Create the rule as a regular expression instead: `^https:\/\/(.+)\.cloudfront.net/.+$`

That should work.

Edit: Fix email mess ups. Why don't they email replies support markdown after I manually edit the comment…?

**Comment by jsit** [comment]
Ah, should have thought of that. Thanks!
