### ISSUE TITLE
Doesn't seem to work on Safari Version 10.1 (12603.1.30.0.34)

### ISSUE THREAD

**Issue by GerTeunis** [infernoboy/JavaScript-Blocker-5#21]
Doesn't install on the latest safari just release a couple of hours ago.

![screen shot 2017-03-28 at 13 32 27](https://cloud.githubusercontent.com/assets/203438/24402935/06996e4e-13bb-11e7-933d-9434fd4c812c.png)

**Comment by cbruno1** [comment]
Same problem for Safari 10.1.1 (11603.2.5).
![error](https://user-images.githubusercontent.com/29424954/27121972-9c0bdc8a-50e9-11e7-8316-d464eeb96f49.jpg)

Concerning Js Blocker 5.2.0 SHA1 is correct: 
`shasum ~/Desktop/JSB5.safariextz` 
`75ab054e262ba1e6662a0fc1d352639c9dc1fc1a`

Maybe is because of Gatekeeper?
`spctl -a -vv ~/Desktop/JSB5.safariextz` 
`~/Desktop/JSB5.safariextz: rejected source=no usable signature`

System Version: OS X 10.11.6 (15G1510)
      `Kernel Version: Darwin 15.6.0`
      `Boot Volume: Macintosh SSD`
      `Boot Mode: Normal`
      `Secure Virtual Memory: Enabled`
      `System Integrity Protection: Enabled`

**Comment by wahlstedt** [comment]
If you downloaded JS Blocker from Apple's extensions gallery, you won't be able to update to the website version; you'll have to uninstall the current version first. If you don't, an error will occur while installing.

**Comment by cbruno1** [comment]
I installed JS Blocker for direct download, I still uninstall JS Blocker and reinstalled and it worked!

Thank you very much!
