### ISSUE TITLE
A question about required permissions

### ISSUE THREAD

**Issue by kyrylo** [infernoboy/JavaScript-Blocker-5#30]
First of all, thanks for the extension! I find it essential.

Next, I'd like to clarify why it needs the following permissions:

* Webpage Contents
* Browsing history

<img width="541" alt="1" src="https://user-images.githubusercontent.com/1079123/44444176-28428080-a60e-11e8-95fa-0909fb7f908f.png">

I can see how it could be a minimum requirement to support the declared functionality, however, could you please elaborate on what *exactly* makes the extension demand these requirements? Maybe even with links to the code.

Thanks!

**Comment by infernoboy** [comment]
It is because JS Blocker must be able to be injected into all web pages, including secure ones. You can see this from the Extension Builder window. Without injecting, JSB simply won't work.

<img width="812" alt="screen shot 2018-09-10 at 9 58 34 pm" src="https://user-images.githubusercontent.com/25857/45333529-ac6c9180-b544-11e8-88a3-3ba81cb9bf0f.png">
