### ISSUE TITLE
Creative Commons does not recommend usage of their license on code

### ISSUE THREAD

**Issue by yxeri** [infernoboy/JavaScript-Blocker-5#4]
https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_use_a_Creative_Commons_license_for_software.3F

They have some suggestions on other open source licenses for source code.

**Comment by infernoboy** [comment]
Thanks for pointing that out. I was never big on licenses and mostly picked one at random since I wasn't too concerned. I'll be changing the license to Apache 2.0. I really have no idea how that works, though. If someone decides to checkout an older commit, they'd have to abide by the older license, wont't they?

**Comment by yxeri** [comment]
Exactly. If someone retrieves the older code they would have to abide to the old license and not the new one.
