### ISSUE TITLE
Can't install upgrade

### ISSUE THREAD

**Issue by wlalos** [infernoboy/JavaScript-Blocker-5#9]
Trying to upgrade v. 5.1.0 to 5.1.1 I receive from Safari a message: Safari can't install this extension. An error occurred while installing the extension "JSB5.safariext (MacBook Pro (13-inch, Late 2011) OS X 10.11.5)

**Comment by infernoboy** [comment]
This error occurs when you have installed the extensions gallery
version of the extension and are trying to overwrite it with the
website version; Apple does not allow that to happen. To switch to the
website version, you'll have to first uninstall the current version.
You should create a backup before doing so by opening the Settings
menu and then clicking Backup.

Unfortunately Apple is a bit slow at pushing out updates to the
gallery which is why this occurs.
